workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.solucnet.tecnicos"
      node: 18
      java: 21
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Generate icons
        script: |
          node generate-icons.js || echo "Icons generation skipped"
      - name: Copy web assets to Android
        script: |
          echo "Copiando archivos web a Android..."
          npx cap copy android
          echo "✅ Archivos copiados"
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - angelsalgadop@gmail.com
        notify:
          success: true
          failure: true
